name: Master Deployment

on:
  push:
    branches:
      - "master"
jobs:
  set_time:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.calculate_time.outputs.timestamp }}
    steps:
      - name: Calculate current timestamp
        id: calculate_time
        run: echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

  build-and-Push:
    runs-on: ubuntu-latest
    environment: develop
    needs: set_time
    env:
      IMAGE_TAG: ${{ needs.set_time.outputs.timestamp }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@main
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{secrets.MAIN_ACR_AZURE_LOGIN_SERVER}}
          username: ${{secrets.MAIN_ACR_ADMIN_USERNAME}}
          password: ${{secrets.MAIN_ACR_ADMIN_PASSWORD}}
      - name: Build Docker Image
        run: |
          docker build . -t ${{secrets.MAIN_DOCKER_IMAGE_NAME}}
          docker image ls

      - name: Tag the Docker Image
        run: |
          docker tag ${{secrets.MAIN_DOCKER_IMAGE_NAME}} ${{secrets.MAIN_ACR_AZURE_LOGIN_SERVER}}/${{secrets.MAIN_DOCKER_IMAGE_NAME}}:latest
          docker tag ${{secrets.MAIN_DOCKER_IMAGE_NAME}} ${{secrets.MAIN_ACR_AZURE_LOGIN_SERVER}}/${{secrets.MAIN_DOCKER_IMAGE_NAME}}:${{env.IMAGE_TAG}}
      - name: Push DockerImage to ACR
        run: |
          docker image ls
          docker push ${{secrets.MAIN_ACR_AZURE_LOGIN_SERVER}}/${{secrets.MAIN_DOCKER_IMAGE_NAME}}:latest
          docker push ${{secrets.MAIN_ACR_AZURE_LOGIN_SERVER}}/${{secrets.MAIN_DOCKER_IMAGE_NAME}}:${{env.IMAGE_TAG}}
  Deploy:
    runs-on: ubuntu-latest
    needs:
      - set_time
      - build-and-Push
    env:
      IMAGE_TAG: ${{ needs.set_time.outputs.timestamp }}
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.MAIN_AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          acrName: ${{secrets.MAIN_ACR_ADMIN_USERNAME}}
          containerAppName: ${{secrets.MAIN_CONTAINER_APP_NAME}}
          resourceGroup: ${{secrets.MAIN_RESOURCE_GROUP_NAME}}
          imageToDeploy: ${{secrets.MAIN_ACR_AZURE_LOGIN_SERVER}}/${{secrets.MAIN_DOCKER_IMAGE_NAME}}:${{env.IMAGE_TAG}}